---

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "default-jdk"
    - "default-jre"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version > "14"

- block:
    - name: Add Open Java 8 PPA
      apt_repository:
        repo: "ppa:openjdk-r/ppa"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java 8
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "openjdk-8-jre"
        - "openjdk-8-jdk"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version < "15"

- name: Install Java 8 on CentOS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.rpm"
    - "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jre-8u45-linux-x64.rpm"
  when: ansible_distribution == "CentOS"

- name: Download zip
  get_url:
    url: "https://github.com/trinityrnaseq/trinityrnaseq/archive/Trinity-v{{ VERSION }}.tar.gz"
    dest: "/tmp/Trinity.tar.gz"

- name: Unzip the package
  unarchive:
    src: "/tmp/Trinity.tar.gz"
    dest: "/opt"
    remote_src: yes

- name: Build executables from source
  make:
    chdir: "/opt/trinityrnaseq-Trinity-v{{ VERSION }}"

- name: Build plugins from source
  make:
    chdir: "/opt/trinityrnaseq-Trinity-v{{ VERSION }}"
    target: "plugins"

- name: Remove temporary files
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/tmp/Trinity.tar.gz"
